python3 main.py --experiment "amr_nlg_t5_small_fine_tuning.yml"
python3 main.py --experiment "amr_nlg_t5_small_prompt_tuning.yml"
python3 main.py --experiment "e2e_nlg_t5_small_fine_tuning.yml"
python3 main.py --experiment "e2e_nlg_t5_small_prompt_tuning.yml"
python3 main.py --experiment "web_nlg_t5_small_fine_tuning.yml"
python3 main.py --experiment "web_nlg_t5_small_prompt_tuning.yml"
